spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 1234
    jpa:
      database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
  h2:
    console:
      enabled: true